# These are supported funding model platforms

github: [tinyhust]
patreon: mediumhust
open_collective: mediumhust
ko_fi: mediumhust
liberapay: mediumhust
issuehunt: mediumhust
custom: [paypal.me/duytoanbk/1]
