# These are supported funding model platforms

github: [tinyhust]
patreon: mediumhust
open_collective: mediumhust
ko_fi: mediumhust
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: mediumhust
issuehunt: mediumhust
otechie: NETBASEJSC
custom: [paypal.me/duytoanbk/1]