coverage:
  status:
    project: off
    patch: off

flag_management:
  individual_flags:
    - name: dummy-test
      paths:
        - ./
      statuses:
        - type: project
          target: 100%
          threshold: 1%
