version: '3.5'

services:
  traefik:
    image: traefik:1.7
    command:
      - --api
      - --docker
      - --docker.domain=traefik.localhost
      - --docker.exposedByDefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.toml:/traefik.toml
      - ./config/acme.json:/acme.json
    ports:
      - 80:80
      - 443:443
      - 8082:8080
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    name: reverse-proxy

