name: tests-auth

on:
  pull_request:
    paths:
      - "examples/microservices/auth/**"

jobs:
  build-auth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test auth
        working-directory: examples/microservices
        run: cd auth && npm install && npm run test:ci
