name: Build TOC

on:
  schedule:
    - cron: "20 4 * * *"
  workflow_dispatch:

defaults:
  run:
    working-directory: ./examples/toc

jobs:
  build_toc:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node-version: [18.12.0]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build TOC
        run: node label.js
